services:
  n8n:
    # Uso sem Dockerfile (com a imagem original)
    # image: n8nio/n8n
    #
    # Uso com Dockerfile:
    build: .
    ports:
      - "5678:5678"
    volumes:
      - ./dotn8n:/home/node/.n8n
    environment:
      GENERIC_TIMEZONE: America/Belem
      N8N_COMMUNITY_PACKAGES_ALLOW_USAGE: true
      # NODE_FUNCTION_ALLOW_EXTERNAL: "n8n-nodes-tavily"
    restart: unless-stopped
    networks:
      - n8n-network

networks:
  n8n-network:
    driver: bridge
